"use client";
import { useActionState, useState } from "react";
import Link from "next/link";
import { trades, serviceStatuses, type ServiceProvider } from "./schema";
import { saveService } from "./actions";
import { Field, FormMessage, SubmitButton } from "@/components/forms";
export function ServiceForm({service, locality = "San Juan", name = ""}: {service?: ServiceProvider; locality?: string; name?: string}) {
  const [state, action] = useActionState(saveService.bind(null, service?.id ?? null), {});
  const [values, setValues] = useState({name: service?.name ?? name, trade: service?.trade ?? "Gasista", license_number: service?.license_number ?? "", license_body: service?.license_body ?? "", description: service?.description ?? "", phone: service?.phone ?? "", locality: service?.locality ?? locality, status: service?.status ?? "activo"});
  const bind = (key: keyof typeof values) => ({name: key, id: key, value: values[key], onChange: (e: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement | HTMLSelectElement>) => setValues({...values, [key]: e.target.value})});
  return <form action={action} className="space-y-8"><FormMessage state={state} /><input type="hidden" name="version" value={service?.updated_at ?? ""} />
    <section className="form-panel"><h2 className="panel-title">Tu oficio</h2><Field label="Nombre o razón social" htmlFor="name"><input className="input" {...bind("name")} placeholder="Ej.: Juan Pérez · Gas y plomería" minLength={2} maxLength={100} required /></Field><Field label="Oficio" htmlFor="trade"><select className="input" {...bind("trade")}>{trades.map(t => <option key={t}>{t}</option>)}</select></Field><Field label="Descripción de tus servicios" htmlFor="description" hint="Trabajos que realizás, zonas, horarios y si atendés urgencias."><textarea className="input min-h-32 resize-y" {...bind("description")} placeholder="Ej.: Instalaciones y reparaciones de gas domiciliario, habilitaciones…" minLength={10} maxLength={3000} required /></Field></section>
    <section className="form-panel"><h2 className="panel-title">Matrícula</h2><div className="grid gap-5 sm:grid-cols-2"><Field label="Número de matrícula" htmlFor="license_number"><input className="input" {...bind("license_number")} maxLength={40} required /></Field><Field label="Entidad que la emitió" htmlFor="license_body" hint="Ej.: ENARGAS, Colegio de Técnicos, ente municipal."><input className="input" {...bind("license_body")} maxLength={100} required /></Field></div><p className="text-xs leading-5 text-muted-foreground">Tu matrícula se muestra como <strong>declarada</strong>. La insignia “Matrícula verificada” la otorga La Higuera después de comprobarla, y se retira si cambiás el número, la entidad o el oficio.</p></section>
    <section className="form-panel"><h2 className="panel-title">Contacto y zona</h2><div className="grid gap-5 sm:grid-cols-2"><Field label="Teléfono / WhatsApp" htmlFor="phone" hint="Con código de área, sin 0 ni 15. Ej.: 2644123456. Es público."><input className="input" {...bind("phone")} inputMode="tel" maxLength={20} required /></Field><Field label="Localidad" htmlFor="locality"><input className="input" {...bind("locality")} placeholder="Ej.: Capital, San Juan" minLength={2} maxLength={80} required /></Field></div></section>
    <section className="form-panel"><Field label="Estado del perfil" htmlFor="status" hint="Solo los perfiles activos son visibles para otras personas."><select className="input" {...bind("status")}>{serviceStatuses.map(s => <option value={s} key={s}>{s === "activo" ? "Activo · visible para todos" : "Pausado · solo lo ves vos"}</option>)}</select></Field></section>
    <div className="flex flex-wrap items-center gap-5"><SubmitButton>{service ? "Guardar cambios" : "Publicar servicio"}</SubmitButton><Link href="/mis-servicios" className="text-sm text-muted-foreground">Cancelar</Link></div><p className="text-xs text-muted-foreground">La Higuera conecta personas. No procesa pagos ni garantiza los trabajos.</p>
  </form>;
}
