import { test, expect } from "@playwright/test";
test("inicio, búsqueda y categorías funcionan sin datos inventados", async ({page}, testInfo) => {
  await page.goto("/");
  await expect(page.getByRole("heading", {name: /Lo que buscás/})).toBeVisible();
  await expect(page.getByRole("button", {name: "Pausar carrusel"})).toBeVisible();
  await page.screenshot({path: testInfo.outputPath("inicio.png"), fullPage: true, animations: "disabled"});
  await page.getByRole("textbox", {name: "Buscar por título"}).fill("bicicleta");
  await page.getByRole("button", {name: "Buscar", exact: true}).click();
  await expect(page).toHaveURL(/q=bicicleta/);
  await page.getByRole("link", {name: "Hogar", exact: true}).click();
  await expect(page).toHaveURL(/category=Hogar/);
  await expect(page.getByRole("textbox", {name: "Buscar por título"})).toHaveValue("bicicleta");
  await page.getByRole("textbox", {name: "Buscar por título"}).fill("mesa");
  await page.getByRole("button", {name: "Buscar", exact: true}).click();
  await expect(page).toHaveURL(/category=Hogar/);
  await expect(page).toHaveURL(/q=mesa/);
  await page.getByRole("link", {name: "Todo", exact: true}).click();
  await expect(page).not.toHaveURL(/category=/);
  await expect(page.getByRole("textbox", {name: "Buscar por título"})).toHaveValue("mesa");
  const overflowing = await page.evaluate(() => document.documentElement.scrollWidth > window.innerWidth);
  expect(overflowing).toBe(false);
});
test("carrusel automático, pausa y navegación manual", async ({page}, testInfo) => {
  await page.clock.install();
  await page.goto("/");
  const first = page.getByRole("button", {name: "Mostrar mensaje 1"});
  const second = page.getByRole("button", {name: "Mostrar mensaje 2"});
  await expect(page.getByRole("button", {name: "Pausar carrusel"})).toBeVisible();
  await expect(first).toHaveAttribute("aria-pressed", "true");
  await page.clock.fastForward(6500);
  await expect(second).toHaveAttribute("aria-pressed", "true");
  await page.getByRole("button", {name: "Pausar carrusel"}).click();
  await page.mouse.move(0, 0);
  await page.clock.fastForward(13000);
  await expect(second).toHaveAttribute("aria-pressed", "true");
  await page.getByRole("button", {name: "Mensaje siguiente"}).click();
  await expect(page.getByRole("heading", {name: /Tu próximo hallazgo/})).toBeVisible();
  await page.screenshot({path: testInfo.outputPath("carrusel-mensaje-3.png"), fullPage: true, animations: "disabled"});
  await page.getByRole("button", {name: "Mensaje siguiente"}).press("ArrowRight");
  await expect(first).toHaveAttribute("aria-pressed", "true");
  await page.getByRole("button", {name: "Reanudar carrusel"}).click();
  await page.mouse.move(0, 0);
  await page.clock.fastForward(6500);
  await expect(second).toHaveAttribute("aria-pressed", "true");
});
test("el carrusel respeta la preferencia de movimiento reducido", async ({page}) => {
  await page.emulateMedia({reducedMotion: "reduce"});
  await page.clock.install();
  await page.goto("/");
  await page.clock.fastForward(20000);
  await expect(page.getByRole("button", {name: "Mostrar mensaje 1"})).toHaveAttribute("aria-pressed", "true");
  await page.getByRole("button", {name: "Mostrar mensaje 3"}).click();
  await expect(page.getByRole("heading", {name: /Tu próximo hallazgo/})).toBeVisible();
});
test("publicar requiere sesión y una URL inexistente no revela datos", async ({page}) => {
  await page.goto("/productos/nuevo");
  await expect(page).toHaveURL(/ingresar/);
  await expect(page.getByRole("heading", {name: "Qué bueno verte de nuevo"})).toBeVisible();
  await page.goto("/productos/00000000-0000-4000-8000-000000000000");
  await expect(page.getByRole("heading", {name: "Este anuncio no está disponible"})).toBeVisible();
});
