"use client";
import { useActionState, useState } from "react";
import Link from "next/link";
import { ImagePlus } from "lucide-react";
import { categories, statuses, type Product } from "./schema";
import { saveProduct } from "./actions";
import { Field, FormMessage, SubmitButton } from "@/components/forms";
import { ProductImage } from "@/components/product-image";
export function ProductForm({product, locality = "San Juan"}: {product?: Product; locality?: string}) {
  const [state, action] = useActionState(saveProduct.bind(null, product?.id ?? null), {});
  const [values, setValues] = useState({title: product?.title ?? "", description: product?.description ?? "", price: product?.price.toString() ?? "", currency: product?.currency ?? "ARS", category: product?.category ?? "Otros", condition: product?.condition ?? "usado", locality: product?.locality ?? locality, status: product?.status ?? "activo"});
  const [removeImage, setRemoveImage] = useState(false);
  const bind = (key: keyof typeof values) => ({name: key, id: key, value: values[key], onChange: (e: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement | HTMLSelectElement>) => setValues({...values, [key]: e.target.value})});
  return <form action={action} className="space-y-8"><FormMessage state={state} /><input type="hidden" name="version" value={product?.updated_at ?? ""} />
    <section className="form-panel"><h2 className="panel-title">Contanos qué publicás</h2><Field label="Título del anuncio" htmlFor="title"><input className="input" {...bind("title")} placeholder="Ej.: Bicicleta urbana rodado 28" minLength={3} maxLength={120} required /></Field><div className="grid gap-5 sm:grid-cols-2"><Field label="Categoría" htmlFor="category"><select className="input" {...bind("category")}>{categories.map(c => <option key={c}>{c}</option>)}</select></Field><Field label="Estado del producto" htmlFor="condition"><select className="input" {...bind("condition")}><option value="usado">Usado</option><option value="nuevo">Nuevo</option></select></Field></div><Field label="Descripción" htmlFor="description" hint="Incluí medidas, detalles y todo lo que ayude a conocer el producto."><textarea className="input min-h-36 resize-y" {...bind("description")} placeholder="¿Qué debería saber la persona interesada?" minLength={10} maxLength={5000} required /></Field></section>
    <section className="form-panel"><h2 className="panel-title">Precio y ubicación</h2><div className="grid gap-5 sm:grid-cols-[1fr_140px]"><Field label="Precio" htmlFor="price" hint="Sin separadores de miles. Podés usar hasta 2 decimales."><input className="input" {...bind("price")} inputMode="decimal" placeholder="0,00" maxLength={15} required /></Field><Field label="Moneda" htmlFor="currency"><select className="input" {...bind("currency")}><option value="ARS">ARS · Pesos</option><option value="USD">USD · Dólares</option></select></Field></div><Field label="Localidad" htmlFor="locality"><input className="input" {...bind("locality")} placeholder="Ej.: Capital, San Juan" minLength={2} maxLength={80} required /></Field></section>
    <section className="form-panel"><h2 className="panel-title">Una foto hace la diferencia <span className="ml-1 text-sm font-normal text-muted-foreground">(opcional)</span></h2>{product?.image_path && <div className="space-y-3"><ProductImage className="max-w-xs rounded-xl" path={product.image_path} title={product.title} /><label className="flex items-center gap-2 text-sm"><input type="checkbox" name="remove_image" checked={removeImage} onChange={e => setRemoveImage(e.target.checked)} />Quitar la imagen actual</label></div>}<div className="rounded-xl border border-dashed border-primary/30 bg-muted/40 p-6"><ImagePlus className="mb-3 size-6 text-primary" /><Field label={product?.image_path ? "Reemplazar imagen" : "Elegí una imagen"} htmlFor="image" hint="JPG, PNG o WebP · Hasta 5 MB y 20 megapíxeles · Sin animación. Si ocurre un error, seleccioná nuevamente el archivo."><input className="block w-full text-sm file:mr-4 file:rounded-lg file:border-0 file:bg-primary/10 file:px-4 file:py-2 file:text-primary" id="image" name="image" type="file" accept="image/jpeg,image/png,image/webp" /></Field></div></section>
    <section className="form-panel"><Field label="Estado del anuncio" htmlFor="status" hint="Solo los anuncios activos son visibles para otras personas."><select className="input" {...bind("status")}>{statuses.map(s => <option value={s} key={s}>{s === "activo" ? "Activo · visible para todos" : s === "pausado" ? "Pausado · solo lo ves vos" : "Vendido · solo lo ves vos"}</option>)}</select></Field></section>
    <div className="flex flex-wrap items-center gap-5"><SubmitButton>{product ? "Guardar cambios" : "Publicar anuncio"}</SubmitButton><Link href="/mis-productos" className="text-sm text-muted-foreground">Cancelar</Link></div><p className="text-xs text-muted-foreground">La Higuera es un sitio de anuncios. No procesa compras ni pagos.</p>
  </form>;
}
