"use client";
import { useActionState, useState } from "react";
import Link from "next/link";
import { buttonVariants } from "@/components/ui/button";
import { REAL_ESTATE, statuses, type Product } from "./schema";
import { saveProduct } from "./actions";
import { ImagePicker, savedImages, type ImageItem } from "./image-picker";
import { Field, FormMessage, SubmitButton } from "@/components/forms";
import type { Catalog } from "@/lib/catalog";
export function ProductForm({product, catalog, locality = "capital"}: {product?: Product; catalog: Pick<Catalog, "categories" | "localities">; locality?: string}) {
  const [state, action] = useActionState(saveProduct.bind(null, product?.id ?? null), {});
  const defaultCategory = catalog.categories.some(c => c.id === "otros") ? "otros" : catalog.categories[0]?.id ?? "";
  const [values, setValues] = useState({title: product?.title ?? "", description: product?.description ?? "", price: product?.price.toString() ?? "", currency: product?.currency ?? "ARS", category_id: product?.category_id ?? defaultCategory, condition: product?.condition ?? "usado", locality_id: product?.locality_id ?? locality, operation: product?.operation ?? "", contact_phone: product?.contact_phone ?? "", contact_email: product?.contact_email ?? "", status: product?.status ?? "activo"});
  const [images, setImages] = useState<ImageItem[]>(() => savedImages(product?.images ?? []));
  const bind = (key: keyof typeof values) => ({name: key, id: key, value: values[key], onChange: (e: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement | HTMLSelectElement>) => setValues({...values, [key]: e.target.value})});
  // Los archivos nuevos viven en el estado (se pueden quitar y reordenar) y se agregan al enviar.
  const submit = (form: FormData) => { form.delete("images"); for (const item of images) if (item.file) form.append("images", item.file); action(form); };
  const ready = catalog.categories.length > 0 && catalog.localities.length > 0;
  return <form action={submit} className="flex flex-col gap-6"><FormMessage state={state} />{!ready && <p role="alert" className="notice notice-error">No pudimos cargar los rubros y las localidades. Recargá la página para intentar de nuevo.</p>}<input type="hidden" name="version" value={product?.updated_at ?? ""} />
    <section className="form-panel" aria-labelledby="p-que"><h2 id="p-que" className="panel-title">Contanos qué publicás</h2><Field label="Título del anuncio" htmlFor="title"><input className="input" {...bind("title")} placeholder="Ej.: Bicicleta urbana rodado 28" minLength={3} maxLength={120} required /></Field><div className="grid gap-5 sm:grid-cols-2"><Field label="Rubro" htmlFor="category_id"><select className="input" {...bind("category_id")}>{catalog.categories.map(c => <option value={c.id} key={c.id}>{c.name}</option>)}</select></Field><Field label="Estado del producto" htmlFor="condition"><select className="input" {...bind("condition")}><option value="usado">Usado</option><option value="nuevo">Nuevo</option></select></Field></div>{values.category_id === REAL_ESTATE && <Field label="Operación" htmlFor="operation" hint="Solo para inmuebles."><select className="input" {...bind("operation")} required><option value="">Elegí una opción</option><option value="venta">Venta</option><option value="alquiler">Alquiler</option></select></Field>}<Field label="Descripción" htmlFor="description" hint="Incluí medidas, detalles y todo lo que ayude a conocer el producto."><textarea className="input min-h-36 resize-y" {...bind("description")} placeholder="¿Qué debería saber la persona interesada?" minLength={10} maxLength={5000} required /></Field></section>
    <section className="form-panel" aria-labelledby="p-precio"><h2 id="p-precio" className="panel-title">Precio y ubicación</h2><div className="grid gap-5 sm:grid-cols-[minmax(0,1fr)_160px]"><Field label="Precio" htmlFor="price" hint="Sin separadores de miles. Podés usar hasta 2 decimales."><input className="input" {...bind("price")} inputMode="decimal" placeholder="0,00" maxLength={15} required /></Field><Field label="Moneda" htmlFor="currency"><select className="input" {...bind("currency")}><option value="ARS">ARS · Pesos</option><option value="USD">USD · Dólares</option></select></Field></div><Field label="Localidad" htmlFor="locality_id"><select className="input" {...bind("locality_id")}>{catalog.localities.map(l => <option value={l.id} key={l.id}>{l.name}</option>)}</select></Field></section>
    <section className="form-panel" aria-labelledby="p-contacto"><div className="flex flex-col gap-1.5"><h2 id="p-contacto" className="panel-title">Contacto</h2><p className="body-sm text-muted-foreground">Se muestran en el anuncio para que te escriban. Para publicarlo activo, completá al menos uno.</p></div><div className="grid gap-5 sm:grid-cols-2"><Field label="Teléfono / WhatsApp" htmlFor="contact_phone" hint="Con código de área, sin 0 ni 15. Ej.: 2644123456."><input className="input" {...bind("contact_phone")} inputMode="tel" autoComplete="tel" maxLength={20} /></Field><Field label="Correo de contacto" htmlFor="contact_email"><input className="input" {...bind("contact_email")} type="email" autoComplete="email" maxLength={254} /></Field></div></section>
    <section className="form-panel" aria-labelledby="p-fotos"><div className="flex flex-col gap-1.5"><h2 id="p-fotos" className="panel-title">Las fotos hacen la diferencia</h2><p className="body-sm text-muted-foreground">Opcional. La primera es la portada.</p></div><ImagePicker items={images} onChange={setImages} title={values.title} /></section>
    <section className="form-panel"><Field label="Estado del anuncio" htmlFor="status" hint="Solo los anuncios activos son visibles para otras personas. Vencen a los 60 días y se renuevan desde Mis anuncios."><select className="input" {...bind("status")}>{statuses.map(s => <option value={s} key={s}>{s === "activo" ? "Activo · visible para todos" : s === "pausado" ? "Pausado · solo lo ves vos" : "Vendido · solo lo ves vos"}</option>)}</select></Field></section>
    <div className="flex flex-wrap items-center gap-5"><SubmitButton disabled={!ready}>{product ? "Guardar cambios" : "Publicar anuncio"}</SubmitButton><Link href="/mis-productos" className={buttonVariants({variant: "ghost", className: "text-muted-foreground"})}>Cancelar</Link></div><p className="caption font-normal text-muted-foreground">La Higuera es un sitio de anuncios. No procesa compras ni pagos.</p>
  </form>;
}
